/**
 * electron-builder config (desktop-app §8). macOS-first; Windows/Linux targets
 * stay buildable but unvalidated (§8.3). The gateway sidecar ships OUTSIDE the
 * asar via extraResources — it must be spawnable as a standalone script.
 * Signing/notarization is intentionally left unset (CI provides identities).
 */
export default {
  appId: 'sg.dami.enterprise-agent',
  productName: 'Enterprise Agent',
  directories: {
    output: 'dist',
    buildResources: 'build',
  },
  files: ['out/**'],
  extraResources: [
    {
      from: 'resources/sidecar',
      to: 'sidecar',
    },
    {
      from: 'resources/icons',
      to: 'icons',
    },
  ],
  asar: true,
  npmRebuild: false,
  mac: {
    icon: 'build/icon.icns', // generated by scripts/gen-icons.mjs
    category: 'public.app-category.productivity',
    target: [{ target: 'dmg' }, { target: 'zip' }], // zip is what electron-updater consumes
    identity: null, // unsigned local builds; CI sets a real identity + notarization
  },
  win: {
    target: [{ target: 'nsis' }],
  },
  linux: {
    target: [{ target: 'AppImage' }],
    category: 'Utility',
  },
  // electron-updater feed (§8.2): GitHub Releases, same repo as the monorepo release flow.
  publish: {
    provider: 'github',
    owner: 'dami-sg',
    repo: 'enterprise-agent',
  },
};
